apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lugx-frontend
  template:
    metadata:
      labels:
        app: lugx-frontend
    spec:
      containers:
      - name: lugx-frontend
        image: docker.io/sheharaa/lugx-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-service
spec:
  type: NodePort
  selector:
    app: lugx-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007

